baseURL = 'https://codersonlych.github.io/'
languageCode = 'en-US'
title = 'Coders Only'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'What We Do'
pageRef = '/what-we-do/'
weight = 20

[[menus.main]]
name = 'Blog'
pageRef = '/blog/'
weight = 30

[[menus.main]]
name = 'Association'
pageRef = '/association/'
weight = 40

[[menus.main]]
name = 'Members'
pageRef = '/members/'
weight = 50

[[menus.main]]
name = 'Sponsors'
pageRef = '/sponsors/'
weight = 60

[[menus.main]]
name = 'Code of Conduct'
pageRef = '/code-of-conduct/'
weight = 70

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.highlight]
    noClasses = false

[params]
cssNakedDay = false

